# Generated by Django 3.2.6 on 2021-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image_uri', models.TextField()),
                ('productCategory', models.TextField()),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=200)),
                ('size', models.TextField()),
            ],
        ),
    ]
