# Generated by Django 3.2.6 on 2021-08-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
