# Generated by Django 3.2.6 on 2021-08-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0004_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='productCategory',
        ),
    ]
