# Generated by Django 3.2.6 on 2021-08-16 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0005_rename_description_product_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datePublished',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
