# Generated by Django 3.2.6 on 2021-08-16 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0007_alter_product_datepublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default=datetime.datetime(2021, 8, 16, 12, 58, 40, 531488, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
