# Generated by Django 3.2.6 on 2021-08-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0012_alter_product_datepublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
