# Generated by Django 3.2.6 on 2021-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0024_auto_20210816_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datePublished',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
