# Generated by Django 3.2.6 on 2021-08-16 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galaksiya_app', '0025_alter_product_datepublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 13, 51, 41, 394307, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
